name: JavaScript Linting

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.jsx'

  pull_request:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.jsx'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: 20

    - name: Cache
      uses: actions/cache@main
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: |
        npm install
        npm install -g eslint

    - name: Lint with ESLint
      run: |
        eslint .
        eslint .
