name: Java Syntax Checker

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'

  pull_request:
    branches: [ main ]
    paths:
      - '**/*.java'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Java 17
        uses: actions/setup-java@main
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check Java Syntax
        run: find . -name '*.java' -exec javac -Xlint:all -Xdiags:verbose -d temp/ {} \;
