name: Python application

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'

  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Cache
      uses: actions/cache@main
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.12
      uses: actions/setup-python@main
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 --version
        flake8 . --count --exit-zero --select=E9,F63,F7,F82 --ignore=E203,F401,F402,F403,F405,F404,F541 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=35 --max-line-length=150 --statistics

    - name: Run Black Check
      run: |
        pip install black
        black --version
        
        exitcode=0
        black --check . || exitcode=$?
        if [ $exitcode -ne 0 ]; then
          echo "Black check failed"
          black . --check --diff --color --verbose
          exit 1
        fi
